// <auto-generated />
using System;
using DATABASPROJEKT___E_HANDEL_ADMIN;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATABASPROJEKT___E_HANDEL_ADMIN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212012434_AddTriggersAndViews")]
    partial class AddTriggersAndViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Elektroniska produkter och tillbehör",
                            Name = "Elektronik"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Mode och kläder för alla",
                            Name = "Kläder"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Produkter för hemmet och trädgården",
                            Name = "Hem & Trädgård"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Sportartiklar och fritidsutrustning",
                            Name = "Sport & Fritid"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Böcker och litteratur",
                            Name = "Böcker"
                        });
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            City = "Stockholm",
                            Email = "IywsIwIsJzU2LSxsIS0v",
                            EmailHash = "hashed_anna@newton.com",
                            Name = "Anna Andersson",
                            PasswordHash = "DemoHashedPassword1",
                            PasswordSalt = "DemoSalt1"
                        },
                        new
                        {
                            CustomerId = 2,
                            City = "Göteborg",
                            Email = "JzArKQIlLyMrLmwhLS8=",
                            EmailHash = "hashed_erik@gmail.com",
                            Name = "Erik Eriksson",
                            PasswordHash = "DemoHashedPassword2",
                            PasswordSalt = "DemoSalt2"
                        },
                        new
                        {
                            CustomerId = 3,
                            City = "Malmö",
                            Email = "LyMwKyMCLTc2Li0tKWwhLS8=",
                            EmailHash = "hashed_maria@outlook.com",
                            Name = "Maria Svensson",
                            PasswordHash = "DemoHashedPassword3",
                            PasswordSalt = "DemoSalt3"
                        });
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            TotalAmount = 15498.00m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped",
                            TotalAmount = 998.00m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Processing",
                            TotalAmount = 2499.00m
                        });
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.OrderRow", b =>
                {
                    b.Property<int>("OrderRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderRowId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderRows");

                    b.HasData(
                        new
                        {
                            OrderRowId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 12999.00m
                        },
                        new
                        {
                            OrderRowId = 2,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 2499.00m
                        },
                        new
                        {
                            OrderRowId = 3,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 299.00m
                        },
                        new
                        {
                            OrderRowId = 4,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 199.00m
                        },
                        new
                        {
                            OrderRowId = 5,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 2499.00m
                        });
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Kraftfull bärbar dator",
                            Name = "Laptop",
                            Price = 12999.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Senaste modellen smartphone",
                            Name = "Smartphone",
                            Price = 8999.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Trådlösa hörlurar med brusreducering",
                            Name = "Hörlurar",
                            Price = 2499.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Bekväm bomulls t-shirt",
                            Name = "T-shirt",
                            Price = 299.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Klassiska blå jeans",
                            Name = "Jeans",
                            Price = 699.00m,
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "Bekväm utomhusstol",
                            Name = "Trädgårdsstol",
                            Price = 499.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "LED-bordslampa",
                            Name = "Lampa",
                            Price = 399.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            Description = "Officiell matchboll",
                            Name = "Fotboll",
                            Price = 349.00m,
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Halkfri yogamatta",
                            Name = "Yogamatta",
                            Price = 299.00m,
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 5,
                            Description = "Populär skönlitteratur",
                            Name = "Roman",
                            Price = 199.00m,
                            StockQuantity = 300
                        });
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Order", b =>
                {
                    b.HasOne("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.OrderRow", b =>
                {
                    b.HasOne("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Product", b =>
                {
                    b.HasOne("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DATABASPROJEKT___E_HANDEL_ADMIN.Schemas.Order", b =>
                {
                    b.Navigation("OrderRows");
                });
#pragma warning restore 612, 618
        }
    }
}
